import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ShoppingBag } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase-server";
import { formatBRL } from "@/lib/types";

export async function StorePageContent({ slug }: { slug: string }) {
  const supabase = await createServerSupabaseClient();
  const { data: store } = await supabase.from("published_stores").select("id,name,slug,description,accent_color").eq("slug", slug).single();
  if (!store) return <main className="grid min-h-screen place-items-center bg-[#080a0c] px-5 text-center text-white"><div><p className="mb-3 text-[#b7f34a]">purpowebbx</p><h1 className="text-3xl font-semibold">Loja não encontrada</h1><Link href="/" className="mt-5 inline-block text-sm text-[#b7f34a]">Voltar para a plataforma</Link></div></main>;
  const { data: products } = await supabase.from("published_products").select("id,name,description,price_cents,store_id,accent_color").eq("store_id", store.id).order("created_at", { ascending: false });
  return <main className="min-h-screen bg-[#080a0c] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-6"><Link href="/" className="text-sm text-[#8b949e]"><ArrowLeft className="mr-2 inline" size={15}/> purpowebbx</Link><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-[#8b949e]">loja digital</span></div></header><div className="mx-auto max-w-5xl px-5 py-16"><div className="mb-12 max-w-2xl"><div className="mb-5 grid h-14 w-14 place-items-center rounded-2xl text-xl font-black text-black" style={{ backgroundColor: store.accent_color ?? "#b7f34a" }}>{store.name.slice(0, 1).toUpperCase()}</div><h1 className="text-5xl font-semibold tracking-[-.05em]">{store.name}</h1><p className="mt-4 text-[#8b949e]">{store.description ?? "Produtos digitais para você evoluir mais rápido."}</p></div>{products?.length ? <div className="grid gap-4 md:grid-cols-3">{products.map((product) => <article key={product.id} className="rounded-2xl border border-white/10 bg-[#101317] p-5"><div className="mb-8 grid h-28 place-items-center rounded-xl bg-white/5"><ShoppingBag style={{ color: product.accent_color ?? store.accent_color }} size={30}/></div><p className="text-xs text-[#7d8790]">Produto digital</p><h2 className="mt-2 font-medium">{product.name}</h2><p className="mt-2 line-clamp-2 text-sm text-[#8b949e]">{product.description}</p><div className="mt-5 flex items-center justify-between"><span className="font-mono text-[#b7f34a]">{formatBRL(product.price_cents)}</span><Link href={`/checkout/${product.id}`} className="rounded-full border border-white/15 px-3 py-2 text-xs hover:border-[#b7f34a]">Comprar <ArrowUpRight className="ml-1 inline" size={13}/></Link></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-white/15 p-12 text-center text-[#8b949e]">Esta loja ainda não publicou produtos.</div>}</div></main>;
}
