"use client";

import { useState } from "react";
import { ArrowLeft, Loader2, LockKeyhole, Mail, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "@/lib/supabase-browser";

export default function AuthPage() {
  const router = useRouter();
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); setMessage(""); const supabase = createBrowserSupabaseClient(); if (mode === "signup") { const { data: signUpData, error: signUpError } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }); if (signUpError) setError(signUpError.message); else if (signUpData.session) router.push("/dashboard"); else setMessage("Conta criada. Se a confirmação de e-mail estiver ativa, confirme o endereço antes de entrar."); } else { const { error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError) setError(signInError.message); else router.push("/dashboard"); } setLoading(false); }
  return <main className="grid min-h-screen place-items-center bg-[#080a0c] px-5 py-10 text-white"><div className="w-full max-w-md"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-[#8b949e] hover:text-white"><ArrowLeft size={16}/> Voltar para o início</Link><div className="mb-8 text-center"><div className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-[#b7f34a] text-xl font-black text-black">p</div><h1 className="text-3xl font-semibold tracking-[-.04em]">{mode === "login" ? "Bem-vindo de volta" : "Crie sua conta"}</h1><p className="mt-3 text-sm text-[#8b949e]">{mode === "login" ? "Entre para gerenciar sua loja." : "Comece a vender seus produtos digitais."}</p></div><form onSubmit={submit} className="space-y-4 rounded-3xl border border-white/10 bg-[#101317] p-6 sm:p-8">{mode === "signup" && <label className="block"><span className="mb-2 block text-sm">Seu nome</span><div className="flex items-center rounded-xl border border-white/10 bg-white/5 px-4"><UserRound size={16} className="text-[#7d8790]"/><input required value={name} onChange={(e) => setName(e.target.value)} className="w-full bg-transparent px-3 py-3 text-sm outline-none" placeholder="João da Silva"/></div></label>}<label className="block"><span className="mb-2 block text-sm">E-mail</span><div className="flex items-center rounded-xl border border-white/10 bg-white/5 px-4"><Mail size={16} className="text-[#7d8790]"/><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full bg-transparent px-3 py-3 text-sm outline-none" placeholder="voce@email.com"/></div></label><label className="block"><span className="mb-2 block text-sm">Senha</span><div className="flex items-center rounded-xl border border-white/10 bg-white/5 px-4"><LockKeyhole size={16} className="text-[#7d8790]"/><input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full bg-transparent px-3 py-3 text-sm outline-none" placeholder="Mínimo de 6 caracteres"/></div></label>{error && <p className="rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</p>}{message && <p className="rounded-xl bg-[#b7f34a]/10 px-4 py-3 text-sm text-[#b7f34a]">{message}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#b7f34a] px-5 py-3.5 text-sm font-semibold text-black disabled:opacity-60">{loading ? <><Loader2 className="mr-2 inline animate-spin" size={16}/> Aguarde...</> : mode === "login" ? "Entrar" : "Criar conta"}</button><button type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); setMessage(""); }} className="w-full py-2 text-sm text-[#b7f34a]">{mode === "login" ? "Ainda não tenho uma conta" : "Já tenho uma conta"}</button></form></div></main>;
}
