"use client";

import { useState } from "react";
import { ArrowLeft, Check, Copy, Loader2 } from "lucide-react";
import Link from "next/link";
import { formatBRL } from "@/lib/types";

export default function CheckoutPage({ params }: { params: { productId: string } }) {
  const [form, setForm] = useState({ buyerName: "", buyerEmail: "", buyerDocument: "" });
  const [result, setResult] = useState<{ qrCode?: string; copyPaste?: string; amountCents?: number } | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, productId: params.productId }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setError(body.error ?? "Não foi possível criar o Pix"); return; } setResult(body); }
  return <main className="min-h-screen bg-[#080a0c] px-5 py-8 text-white"><div className="mx-auto max-w-lg"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-[#8b949e]"><ArrowLeft size={16}/> Voltar</Link><div className="mb-8"><p className="mb-3 text-xs uppercase tracking-[.2em] text-[#b7f34a]">Checkout seguro</p><h1 className="text-4xl font-semibold tracking-[-.04em]">Finalize seu Pix.</h1><p className="mt-3 text-sm text-[#8b949e]">Preencha os dados para gerar o pagamento. O produto será enviado ao e-mail após a confirmação.</p></div>{result ? <section className="rounded-3xl border border-[#b7f34a]/30 bg-[#101317] p-6 text-center"><Check className="mx-auto mb-4 text-[#b7f34a]" size={30}/><h2 className="text-xl font-semibold">Pix gerado</h2>{result.amountCents && <p className="mt-2 text-[#b7f34a]">{formatBRL(result.amountCents)}</p>}{result.qrCode?.startsWith("data:image") && <img src={result.qrCode} alt="QR Code Pix" className="mx-auto my-6 h-56 w-56 rounded-xl bg-white p-2"/>}<p className="mb-2 text-left text-xs text-[#8b949e]">Código copia-e-cola</p><div className="flex gap-2"><input readOnly value={result.copyPaste ?? ""} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-xs text-[#cdd2d6]"/><button onClick={() => navigator.clipboard.writeText(result.copyPaste ?? "")} className="rounded-xl bg-[#b7f34a] px-4 text-black"><Copy size={16}/></button></div><p className="mt-5 text-xs text-[#7d8790]">Após o pagamento, aguarde a confirmação automática.</p></section> : <form onSubmit={submit} className="space-y-5 rounded-3xl border border-white/10 bg-[#101317] p-6"><label className="block"><span className="mb-2 block text-sm">Nome completo</span><input required value={form.buyerName} onChange={(e) => setForm({ ...form, buyerName: e.target.value })} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/></label><label className="block"><span className="mb-2 block text-sm">E-mail de entrega</span><input required type="email" value={form.buyerEmail} onChange={(e) => setForm({ ...form, buyerEmail: e.target.value })} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/></label><label className="block"><span className="mb-2 block text-sm">CPF</span><input required value={form.buyerDocument} onChange={(e) => setForm({ ...form, buyerDocument: e.target.value })} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/></label>{error && <p className="rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#b7f34a] px-5 py-3.5 text-sm font-semibold text-black disabled:opacity-60">{loading ? <><Loader2 className="mr-2 inline animate-spin" size={16}/> Gerando Pix...</> : "Gerar pagamento Pix"}</button></form>}</div></main>;
}
