"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Check, Loader2, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { createBrowserSupabaseClient } from "@/lib/supabase-browser";

export default function SettingsPage() {
  const [storeId, setStoreId] = useState(""); const [slug, setSlug] = useState(""); const [clientId, setClientId] = useState(""); const [clientSecret, setClientSecret] = useState(""); const [customDomain, setCustomDomain] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { const supabase = createBrowserSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from("stores").select("id,slug,custom_domain,mistic_client_id").eq("owner_id", user.id).limit(1).maybeSingle(); if (data) { setStoreId(data.id); setSlug(data.slug); setCustomDomain(data.custom_domain ?? ""); setClientId(data.mistic_client_id ?? ""); } })(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/stores/gateway", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ storeId, clientId, clientSecret, customDomain }) }); const body = await response.json(); setSaving(false); setMessage(response.ok ? body.message : body.error); }
  return <main className="min-h-screen bg-[#080a0c] px-5 py-8 text-white"><div className="mx-auto max-w-2xl"><Link href="/dashboard" className="mb-10 inline-flex items-center gap-2 text-sm text-[#8b949e]"><ArrowLeft size={16}/> Voltar ao painel</Link><p className="mb-3 text-xs uppercase tracking-[.2em] text-[#b7f34a]">Configurações da loja</p><h1 className="text-4xl font-semibold tracking-[-.04em]">Conecte seu recebimento.</h1><p className="mt-3 text-sm text-[#8b949e]">Cada vendedor usa sua própria conta MisticPay. O purpowebbx apenas orquestra o checkout e aplica a comissão configurada.</p><form onSubmit={save} className="mt-8 space-y-5 rounded-3xl border border-white/10 bg-[#101317] p-6 sm:p-8"><div className="rounded-2xl bg-[#b7f34a]/10 p-4 text-sm text-[#d6fa8c]"><ShieldCheck className="mr-2 inline" size={17}/> Use uma Access Key atual da MisticPay (`pk_` + `sk_`). A chave secreta será criptografada antes de ser salva.</div><label className="block"><span className="mb-2 block text-sm">Client ID / chave pública</span><input required value={clientId} onChange={(e) => setClientId(e.target.value)} placeholder="pk_..." className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/></label><label className="block"><span className="mb-2 block text-sm">Client Secret / chave secreta</span><input required type="password" value={clientSecret} onChange={(e) => setClientSecret(e.target.value)} placeholder="sk_..." className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/></label><label className="block"><span className="mb-2 block text-sm">Domínio personalizado opcional</span><input value={customDomain} onChange={(e) => setCustomDomain(e.target.value)} placeholder="loja.seudominio.com" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[#b7f34a]/60"/><p className="mt-2 text-xs text-[#7d8790]">URL automática: {slug ? `${slug}.purpowebbx.com` : "seu-slug.purpowebbx.com"}</p></label>{message && <p className="rounded-xl bg-[#b7f34a]/10 px-4 py-3 text-sm text-[#b7f34a]">{message}</p>}<button disabled={!storeId || saving} className="w-full rounded-xl bg-[#b7f34a] px-5 py-3.5 text-sm font-semibold text-black disabled:opacity-60">{saving ? <><Loader2 className="mr-2 inline animate-spin" size={16}/> Salvando...</> : <><Check className="mr-2 inline" size={16}/> Salvar integração</>}</button></form></div></main>;
}
